---
title: Commetns from Dr. Carl Henrik Knutsen
format:
  hikmah-response-typst: default
bibliography: references.bib
---

In this memo, I do not include the comments related to simple writing issues and
describe how I plan to revise the paper in response to the comments from Dr.
Knutsen (Hereafter CHK). CHK's comments are cited or summarized in [red
italicized text]{.memo-reviewer-inline}, and my responses are in black Roman
text. I include expected revisions and excerpts from the revised manuscript in
[blue]{.memo-excerpt-inline}. Also, please see the detailed updates for the
robustness checks.

# CHK's Comments

## Abstract

::: memo-excerpt
**Before**: I examine data on authoritarian regimes and their welfare provisions
from 1966-2011. I find that mass-based coalitions and strong mass party
organizations lead to more universal welfare. [Also, the effect of mass-based
coalition diminishes when autocrats effectively manage information problems with
a well-institutionalized mass party, reducing the need for universal welfare
provisions.]{.underline}
:::

::: memo-reviewer
CHK: "explicitly tie party organization's to resolving the information problem?"
:::

I understand CHK's concern that the existing abstract does not clarify the logic
behind why mass party organizations interact with mass-based coalitions for
universal welfare provision as a testable hypothesis, despite the fact that I
have described the broad arguments above. Thus, I intend to improve the abstract
as follows:

::: memo-excerpt
**After**: I examine data on authoritarian regimes and their welfare provisions
from 1966-2011. I find that mass-based coalitions and strong mass party
organizations lead to more universal welfare. [Also, the effect of mass-based
coalition diminishes when autocrats effectively manage information problems
through a well-institutionalized mass party.]{.underline} [Strong mass party
organizations play an important role in resolving information problems, enabling
more efficient targeting, and reducing reliance on universal welfare
provisions.]{.underline}
:::

## Introduction

### First Paragraph on Page 2

::: memo-excerpt
**Before**: For example, China, [a typical authoritarian regime]{.underline},
has a social assistance program providing unconditional cash transfers to
protect minimum-income earners (Pan 2020).
:::

::: memo-reviewer
CHK: "what does "typical" mean here? specify"
:::

How about removing the unnecessary description 'a typical authoritarian
regime?':

::: memo-excerpt
**After**: For example, China has has a social assistance program providing
unconditional cash transfers to protect minimum-income earners (Pan 2020).
:::

### Second Paragraph on Page 3

::: memo-excerpt
**Before**: Using time-series cross-sectional (TSCS) [data from 87 to 98
autocratic states, this study investigates the relationship between the nature
of the ruling coalition]{.underline}, the level of mass party organization, and
the scope of welfare provision over time, ensuring rigorous analysis by
including fixed effects for countries and years.
:::

::: memo-reviewer
CHK: "almost 100 or "up to 98""
:::

I would like to revise the manuscript based on the latter suggestion, but I'm
not sure why CHK suggested changing this:

::: memo-excerpt
**After**: Using time-series cross-sectional (TSCS) data from [up to 98
autocratic states, this study investigates the relationship between the nature
of the ruling coalition]{.underline}, the level of mass party organization, and
the scope of welfare provision over time, ensuring rigorous analysis by
including fixed effects for countries and years.
:::

::: memo-excerpt
**Before**: This paper tests theoretical arguments with data on authoritarian
regimes and welfare provisions from 1966 to 2011, showing that authoritarian
welfare provision is dependent on the ruling coalition in place, but the
underlying rationale is based on mechanisms for resolving information problems.
Using time-series cross-sectional (TSCS) data from up to 98 autocratic states,
this study investigates the relationship between the nature of the ruling
coalition, the level of mass party organization, and the scope of welfare
provision over time, ensuring rigorous analysis by including fixed effects for
countries and years.The findings show that while mass-based coalitions increase
universal welfare, the effect diminishes when autocrats can effectively manage
information problems, reducing the need for broad welfare provisions. It adds to
our understanding of authoritarian regimes by emphasizing the role of
institutionalization and coalition management in welfare distribution, providing
insights into how autocratic leaders use institutions to consolidate power.
:::

::: memo-reviewer
CHK: "say something about the measures/proxies of information handling already
here? Otherwise very nice and clear!"
:::

I provides a theoretical framework for understanding the problems autocrats face
in obtaining accurate information, particularly in non-democratic settings where
there are no established mechanisms for gathering information about the ruling
coalition (or population autocrats should co-opt). Some authoritarian states try
to mitigate these problems by establishing quasi-democratic institutions, such
as political parties. Hence, as explained in the Research Design section, where
I provide a brief introduction to empirical measures that I will use, I would
like to revise the manuscript to highlight the significance of mass party
organization as a crucial mechanism employed by autocrats to address information
problems, akin to the suggested edits for the abstract:

::: memo-excerpt
**After**: This paper tests theoretical arguments with data on authoritarian
regimes and welfare provisions from 1966 to 2011, showing that authoritarian
welfare provision is dependent on the ruling coalition in place, but the
underlying rationale is based on mechanisms for resolving information problems.
[I expect that strong mass party organizations have a significant impact on
addressing information problems, facilitating more effective targeting, and
diminishing dependence on universal welfare provisions.]{.underline} Using
time-series cross-sectional (TSCS) data from up to 98 autocratic states, this
study investigates the relationship between the nature of the ruling coalition,
the level of mass party organization, and the scope of welfare provision over
time, [with rigorous analysis including fixed effects for countries and
years]{.underline}. The findings show that while mass-based coalitions increase
universal welfare, the effect diminishes when autocrats can effectively manage
information problems, reducing the need for broad welfare provisions. It adds to
our understanding of authoritarian regimes by emphasizing the role of
institutionalization and coalition management in welfare distribution,providing
insights into how autocratic leaders use institutions to consolidate power.
:::

## Theory

### Last Paragraph on Page 7

::: memo-excerpt
**Before**: Autocrats can mitigate elite threats by sharing power with them and
establishing credible commitments that include granting elites opportunities to
participate in formal institutions (Svolik 2012). When the ruling coalition with
elites becomes institutionalize, it is more likely to have exclusive
memberships, making their source of power immobile(Geddes,Wright and Frantz
2018). Such an institution-based coalition with elites encourages elite members
to have a more convergent preference for specific social policies or selective
welfare provisions, in the sense that they lose influence as soon as they leave
the institution.
:::

::: memo-reviewer
CHK: "see, e.g., Knutsen and Rasmussen 2018 for an argument on how major welfare
programs (with large sunk costs and identifiable if taken away/scaled down) may
function as credible commitment devices, sometimes even without institutional
changes."
:::

The rationale behind my revision was to integrate the findings of Knutsen and
Rasmussen (2018) on the role of substantial sunk costs in welfare programs as
reliable commitments. I intended to revise this part to support the argument
that welfare provisions can be a tool to ensure the loyalty of the elite based
on the comment from CHK:

::: memo-excerpt
**After**: Autocrats can mitigate [threats from elites by sharing power
and]{.underline} establishing credible commitments that include [providing
elites with opportunities to participate in formal institutions]{.underline}
(Svolik 2012). When the ruling coalition with elites becomes institutionalized,
it is more likely to have exclusive memberships, making their source of power
immobile (Geddes,Wright and Frantz 2018). Such [an institution-based coalition
can create a more convergent preference for specific social policies, including
selective welfare provisions, because]{.underline} elites [should bare
significant sunk costs (Knutsen and Rasmussen 2018)]{.underline} and lose
influence as soon as they leave the institution.
:::

### Second Paragraph on Page 10

::: memo-excerpt
**Before**: This brings us to a critical intersection: mass-based coalition
building and strategic use of mass party organizations. While mass-based
coalitions necessitate some level of universal welfare to ensure widespread
appeasement, mass party organizations offer away to refine the regime’s welfare
provisions. The improved information flow allows for a more targeted welfare
strategy, potentially reducing universal welfare benefits. As a result, it
suggests that welfare provisions should be strategically calibrated not just for
broad appeasement, but also to maintain support for potentially less universal
welfare provisions.

**Hypothesis 3**: *The amount of universal welfare an autocrat provides to
mass-based coalition diminishes with greater mass party institutionalization*.
:::

::: memo-reviewer
CHK: "This H3 is a key hypotheses, so I think you may need to spell out and
clarify the interaction logic even more. Exactly why is it that these are
"substitutes" in resolving the info problem, and (discuss potential counter-arg
such as:) why shouldn't mass based parties for example empower larger groups to
make them have more effective demands on autocrats, and thus push up welfare
provision?"
:::

*Want to have a chat with MCW:*

::: memo-excerpt
**After**: *Not yet.*
:::

## Research Design

### Third Paragraph on Page 10

::: memo-reviewer
CHK: "ok, but note that RoW gives a fairly high threshold for counting regimes
as democracies, so likely to include regimes that many other measures consider
democratic. Worth highlighting already here if you try out different measures
for delineating sample in rob tests."
:::

#### Overview With Different Measurements of Regime

I have examined the identical specifications (benchmark models and full models)
using three distinct regime measures: @boix2013Complete, @skaaning2015Lexical,
and @geddes2014Autocratic.

The results are consistent, except for the interaction terms, when I use the
@geddes2014Autocratic model. *Want to have a chat with MCW:*

::: memo-excerpt
**After**: *Not yet.*
:::

### Second Paragraph on Page 11

::: memo-reviewer
CHK: "how robust are results to including such lags a few years back in time?
The risk of omitting relates to confounding from similar trends or reverse
causality (welfare in t-2 might affect both covariates in t-1 and outcome in t).
Think it is fair to stick with the specification you have, but some more
discussion potential issues and if needed some extra tests might be good to
convince skeptics."
:::

*Want to have a chat with MCW:*

::: memo-excerpt
**After**: *Not yet.*
:::

### First Paragraph on Page 13

::: memo-excerpt
**Before**: In particular, mass-based coalitions mainly consistof working
classes and includes several states; Bolivia, Vietnam, Argentina, Nicaragua,and
Ukraine. Those autocracies with mass-based coalitions account for 2.4 percent of
allcoalition observations in the sample.
:::

::: memo-reviewer
CHK: "This is fairly low, since "most important group" sets a very high
threshold for capturing group relevance. It could be worth also using different
rules such as at least one mass based support group in the coalition (using
x\>=0.5 on the multiple choice support group variables, capturing if half or
more of experts think the group is part of coalition -- this is the rule I
typically apply myself in different papers (under review, most of them
unfortuantely, so not yet publsihed)."
:::

*Want to have a chat with MCW:*

::: memo-excerpt
**After**: *Not yet.*
:::

### First Paragraph on Page 16 and Third Paragraph on Page 17

::: memo-excerpt
**Before**: I control the ability of a regime to use repression possible
influence of repression strategies using the stan- 15dardized and reversed human
rights protection score of (Schnakenberg and Fariss 2014; Fariss 2014), which
shows that higher values indicate more state-led repression (Chin, Song and
Wright 2023). ... I control two measures to show whether civilsocieties are
associated with the welfare universality is controlled. One measures if
civilsociety organizations (CSOs) routinely consults with policymakers, while
another showsthe extent of CSOs’ participatory environment.
:::

::: memo-reviewer
CHK: "Repression could also be post treatment, if depends on opportunities/costs
of co-optation, so should perhaps also check model w.o. repression as rob test."
... "this could be endogenous to party structures, so worth checking also
specification without this one."
:::

The results are consistent when I exclude repression, civil war experience, CSO
consults, CSO participation, or both from the full model specifications
(additive and multiplicative). *Want to have a chat with MCW:*

::: memo-excerpt
**After**: *Not yet.*
:::

## Empirical Analysis

### Figure 2 on Page 20

::: memo-reviewer
CHK:

-   "Ok so this line is without Vietnam? That suggests the finding is pretty
    sensitive. strange that one country matters so much, and that no other
    omission of countries gives similar lines, but then I guess it's important
    to do various rob tests on this sample excluding Vietnam to see if you can
    recover the relationship e.g. if you kick out control variables or make
    other alterations."

-   Again, given that results are so senstive to Vietnam, I think it is extra
    important to show several other rob tests (different control strategies,
    different delineations of the sample using other measures that ROW, other
    measures of the main variables, etc) to see if it is robust for full
    sample/equally sensitive to Vietnam for other plausible specifications
:::

*Want to have a chat with MCW:*

::: memo-excerpt
**After**: *Not yet.*
:::
